name: Planner CI
on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - release/*
    tags:
      - '*.*.*'
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  build:
    name: Build and analyze
    uses: ./.github/workflows/dotnet.yml
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
    with:
      sonar: false
      publish: ${{ github.event_name != 'pull_request' }}
  package:
    name: Build image and push to registry
    uses: ./.github/workflows/deploy.yml
    if: success() && github.event_name != 'pull_request'
    needs: build
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      ssh-host: ${{ secrets.SSH_HOST }}
      ssh-port: ${{ secrets.SSH_PORT }}
      ssh-username: ${{ secrets.SSH_USERNAME }}
      ssh-key: ${{ secrets.SSH_KEY }}
      postgres-username: ${{ secrets.POSTGRES_USERNAME }}
      postgres-password: ${{ secrets.POSTGRES_PASSWORD }}
    with:
      registry: ghcr.io/ecole-marie-marvingt
      image-name: planner/api
      push: ${{ startsWith(github.ref, 'refs/tags/') }}
      deploy: ${{ startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write